version: '3'

services:
    #Contenedor A
    mongo:
        image: mongo
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
          - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
          - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
          - MONGO_INITDB_DATABASE=$MONGO_DB
        volumes:
          - dbdata:/data/db
        networks:
          - app-network

    #Contenedor C
    generator:
        container_name: generator
        build:
            context: .
            dockerfile: dockerfile.generator
        container_name: generator
        restart: unless-stopped
        command: sh Puertos/Generator/wait-for.sh localhost:27017
        command: python3 Puertos/Generator/Executer.py
        networks: 
            - app-network
        depends_on: 
            - mongo
        links:
            - mongo:mongo



volumes:
    dbdata:
networks:
    app-network:
        driver: bridge