version: '3'

services:
    #Contenedor A
    mongo:
        image: mongo
        container_name: db
        restart: on-failure:10
        env_file: .env
        environment:
          - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
          - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
          - MONGO_INITDB_DATABASE=$MONGO_DB
        volumes:
          - dbdata:/data/db
        networks:
          - app-network
    #Contenedor B
    mongo-express:
        image: mongo-express:latest
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_BASICAUTH_USERNAME: admin
          ME_CONFIG_BASICAUTH_PASSWORD: admin2021!
          ME_CONFIG_MONGODB_PORT: 27017
          ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
          ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
        links:
          - mongo:mongo
        networks:
          - app-network
        depends_on:
          - mongo
    #Contenedor C
    generator:
        container_name: generator
        build:
            context: .
            dockerfile: dockerfile.generator
        restart: on-failure:10
        command: sh Puertos/Generator/wait-for.sh mongo:27017
        command: python3 Puertos/Generator/Executer.py
        networks: 
            - app-network
        depends_on: 
            - mongo
        links:
            - mongo:mongo
    #Contenedor D
    booksapi:
      container_name: API
      build:
          context: ./Puertos/API
          dockerfile: dockerfile
      restart: on-failure:10
      depends_on: 
          - mongo
      networks: 
        - app-network
      ports:
        - 5000:5000
      links:
        - mongo:mongo
      depends_on:
        - mongo
      environment:
        PORT: 5000


volumes:
    dbdata:
networks:
    app-network:
        driver: bridge