version: '3'

services:

    mongo:
        container_name: mongodb
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=project
        ports: 
            - "27017:27017"

    mongo-express:
        container_name: mongodbms
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=localhost
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
            - ME_CONFIG_BASICAUTH_USERNAME=DASistemas
            - ME_CONFIG_BASICAUTH_PASSWORD=Ordinario!
        depends_on:
            - mongo
        ports:
          - "8888:8081"

    generator:
        container_name: generator
        build: 
            context: .
            dockerfile: dockerfile.generator
        depends_on:
            - mongo
            - mongo-express